/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as QTokenRouteImport } from './routes/q.$token'
import { Route as PayTokenRouteImport } from './routes/pay.$token'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppCatalogRouteImport } from './routes/_app/catalog'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppQuotesIndexRouteImport } from './routes/_app/quotes/index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiPaymentsStripeWebhookRouteImport } from './routes/api/payments/stripe-webhook'
import { Route as ApiCronMarkOverdueRouteImport } from './routes/api/cron/mark-overdue'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppQuotesNewRouteImport } from './routes/_app/quotes/new'
import { Route as AppQuotesQuoteIdRouteImport } from './routes/_app/quotes/$quoteId'
import { Route as AppInvoicesNewRouteImport } from './routes/_app/invoices/new'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/_app/invoices/$invoiceId'
import { Route as AppContactsNewRouteImport } from './routes/_app/contacts/new'
import { Route as AppContactsContactIdRouteImport } from './routes/_app/contacts/$contactId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const QTokenRoute = QTokenRouteImport.update({
  id: '/q/$token',
  path: '/q/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsStripeWebhookRoute =
  ApiPaymentsStripeWebhookRouteImport.update({
    id: '/api/payments/stripe-webhook',
    path: '/api/payments/stripe-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronMarkOverdueRoute = ApiCronMarkOverdueRouteImport.update({
  id: '/api/cron/mark-overdue',
  path: '/api/cron/mark-overdue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppQuotesNewRoute = AppQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesQuoteIdRoute = AppQuotesQuoteIdRouteImport.update({
  id: '/quotes/$quoteId',
  path: '/quotes/$quoteId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsNewRoute = AppContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsContactIdRoute = AppContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/billing': typeof AppBillingRoute
  '/catalog': typeof AppCatalogRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/q/$token': typeof QTokenRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/contacts/new': typeof AppContactsNewRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/quotes/new': typeof AppQuotesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/mark-overdue': typeof ApiCronMarkOverdueRoute
  '/api/payments/stripe-webhook': typeof ApiPaymentsStripeWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/quotes/': typeof AppQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/billing': typeof AppBillingRoute
  '/catalog': typeof AppCatalogRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/q/$token': typeof QTokenRoute
  '/': typeof AppIndexRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/contacts/new': typeof AppContactsNewRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/quotes/new': typeof AppQuotesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/mark-overdue': typeof ApiCronMarkOverdueRoute
  '/api/payments/stripe-webhook': typeof ApiPaymentsStripeWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/contacts': typeof AppContactsIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/quotes': typeof AppQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/catalog': typeof AppCatalogRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/q/$token': typeof QTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/contacts/$contactId': typeof AppContactsContactIdRoute
  '/_app/contacts/new': typeof AppContactsNewRoute
  '/_app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/_app/quotes/new': typeof AppQuotesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/mark-overdue': typeof ApiCronMarkOverdueRoute
  '/api/payments/stripe-webhook': typeof ApiPaymentsStripeWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/quotes/': typeof AppQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/signup'
    | '/billing'
    | '/catalog'
    | '/onboarding'
    | '/settings'
    | '/accept-invitation/$invitationId'
    | '/pay/$token'
    | '/q/$token'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/api/auth/$'
    | '/api/cron/mark-overdue'
    | '/api/payments/stripe-webhook'
    | '/api/trpc/$'
    | '/contacts/'
    | '/invoices/'
    | '/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/signup'
    | '/billing'
    | '/catalog'
    | '/onboarding'
    | '/settings'
    | '/accept-invitation/$invitationId'
    | '/pay/$token'
    | '/q/$token'
    | '/'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/api/auth/$'
    | '/api/cron/mark-overdue'
    | '/api/payments/stripe-webhook'
    | '/api/trpc/$'
    | '/contacts'
    | '/invoices'
    | '/quotes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/signup'
    | '/_app/billing'
    | '/_app/catalog'
    | '/_app/onboarding'
    | '/_app/settings'
    | '/accept-invitation/$invitationId'
    | '/pay/$token'
    | '/q/$token'
    | '/_app/'
    | '/_app/contacts/$contactId'
    | '/_app/contacts/new'
    | '/_app/invoices/$invoiceId'
    | '/_app/invoices/new'
    | '/_app/quotes/$quoteId'
    | '/_app/quotes/new'
    | '/api/auth/$'
    | '/api/cron/mark-overdue'
    | '/api/payments/stripe-webhook'
    | '/api/trpc/$'
    | '/_app/contacts/'
    | '/_app/invoices/'
    | '/_app/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  PayTokenRoute: typeof PayTokenRoute
  QTokenRoute: typeof QTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronMarkOverdueRoute: typeof ApiCronMarkOverdueRoute
  ApiPaymentsStripeWebhookRoute: typeof ApiPaymentsStripeWebhookRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/q/$token': {
      id: '/q/$token'
      path: '/q/$token'
      fullPath: '/q/$token'
      preLoaderRoute: typeof QTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog': {
      id: '/_app/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/': {
      id: '/_app/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/stripe-webhook': {
      id: '/api/payments/stripe-webhook'
      path: '/api/payments/stripe-webhook'
      fullPath: '/api/payments/stripe-webhook'
      preLoaderRoute: typeof ApiPaymentsStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/mark-overdue': {
      id: '/api/cron/mark-overdue'
      path: '/api/cron/mark-overdue'
      fullPath: '/api/cron/mark-overdue'
      preLoaderRoute: typeof ApiCronMarkOverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/quotes/new': {
      id: '/_app/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AppQuotesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/$quoteId': {
      id: '/_app/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof AppQuotesQuoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$invoiceId': {
      id: '/_app/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/new': {
      id: '/_app/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AppContactsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/$contactId': {
      id: '/_app/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AppContactsContactIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppContactsContactIdRoute: typeof AppContactsContactIdRoute
  AppContactsNewRoute: typeof AppContactsNewRoute
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppQuotesQuoteIdRoute: typeof AppQuotesQuoteIdRoute
  AppQuotesNewRoute: typeof AppQuotesNewRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppContactsContactIdRoute: AppContactsContactIdRoute,
  AppContactsNewRoute: AppContactsNewRoute,
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppQuotesQuoteIdRoute: AppQuotesQuoteIdRoute,
  AppQuotesNewRoute: AppQuotesNewRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  PayTokenRoute: PayTokenRoute,
  QTokenRoute: QTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronMarkOverdueRoute: ApiCronMarkOverdueRoute,
  ApiPaymentsStripeWebhookRoute: ApiPaymentsStripeWebhookRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
