// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv"
import { fileURLToPath } from "node:url"
import { defineConfig } from "prisma/config"
import { discoverWorkspaceEnvFile } from "../../scripts/workspace-env.js"

const prismaConfigDir = fileURLToPath(new URL(".", import.meta.url))
const envFile = discoverWorkspaceEnvFile({ cwd: prismaConfigDir })
if (envFile) {
  dotenv.config({ path: envFile })
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
})
